// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eghsaocswdkxmoiabeqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnaHNhb2Nzd2RreG1vaWFiZXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzEzODksImV4cCI6MjA3MTU0NzM4OX0.UoPTUuI0TkdOuNjnCXAyoQv0jyM7kV1epYGPI2iZOxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});